//
//  FileHeader.swift
//  ContractSwiftTests
//
//  Created by Daisuke Sato on 2018/03/13.
//

import Foundation

struct FileHeaderPrinter: Printable {
    func print() -> String {
        return [
            "//",
            "// This is a generated file, do not edit!",
            "// Generated by Contractswift, see https://github.com/daisuke310vvv/ContractSwift.git",
            "//",
            ].joined(separator: "\n")
    }
}
